name: ado-llm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.14
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - about-time==4.2.1
      - absl-py==2.1.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - alive-progress==3.1.5
      - annotated-types==0.6.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autograd==1.6.2
      - botorch==0.12.0
      - catboost==1.2.5
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - cma==3.2.2
      - cmaes==0.10.0
      - cmake==3.29.2
      - colorlog==6.8.2
      - comm==0.2.2
      - configspace==0.7.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.10
      - dask==2024.4.2
      - dataclasses-json==0.6.4
      - debugpy==1.8.1
      - decorator==5.1.1
      - deprecated==1.2.14
      - dill==0.3.8
      - distributed==2024.4.2
      - distro==1.9.0
      - emcee==3.1.4
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - filelock==3.13.4
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - gpy==1.10.0
      - gpytorch==1.13
      - grapheme==0.6.0
      - greenlet==3.0.3
      - h11==0.14.0
      - h5py==3.9.0
      - hebo==0.3.5
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.7
      - importlib-metadata==7.1.0
      - ipykernel==6.29.4
      - ipython==8.24.0
      - jax==0.2.24
      - jaxtyping==0.2.19
      - jedi==0.19.1
      - jinja2==3.1.3
      - jiter==0.7.0
      - joblib==1.4.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - langchain==0.1.9
      - langchain-community==0.0.34
      - langchain-core==0.1.46
      - langsmith==0.1.51
      - liac-arff==2.5.0
      - lightgbm==4.3.0
      - linear-operator==0.5.3
      - lit==18.1.4
      - locket==1.0.0
      - mako==1.3.3
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - minio==7.2.6
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - mypy-extensions==1.0.0
      - nashpobench2api==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.23.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openai==1.54.3
      - openml==0.14.2
      - opt-einsum==3.3.0
      - optuna==3.3.0
      - orjson==3.10.1
      - packaging==23.2
      - pandas==1.3.5
      - paramz==0.9.6
      - parso==0.8.4
      - partd==1.4.1
      - parzen-estimator==0.5.8
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.1
      - plotly==5.21.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyaml==24.4.0
      - pyarrow==12.0.1
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pygments==2.18.0
      - pymoo==0.6.1.1
      - pynisher==0.6.4
      - pyparsing==3.1.2
      - pyrfr==0.9.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - regex==2024.4.16
      - requests==2.31.0
      - scikit-learn==1.0.2
      - scikit-optimize==0.9.0
      - scipy==1.12.0
      - six==1.16.0
      - smac==1.4.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - sympy==1.12
      - tblib==3.0.0
      - tenacity==8.2.3
      - threadpoolctl==3.4.0
      - tiktoken==0.6.0
      - toolz==0.12.1
      - torch==2.0.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.3
      - triton==2.0.0
      - typeguard==4.4.1
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - uncertainty-toolbox==0.1.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - wrapt==1.16.0
      - xgboost==2.0.3
      - xmltodict==0.13.0
      - yarl==1.9.4
      - zict==3.0.0
      - zipp==3.18.1
